---
- hosts: all
  tasks:
    - name: Check sshd state
      ansible.builtin.service: # systemctl start sshd
        name: sshd
        state: started

    - name: Check rsyslog state
      ansible.builtin.service:
        name: rsyslog
        state: started 
