---
- hosts: localhost #ansible_server임
  tasks:
    - name: loop echo test
      ansible.builtin.shell: "echo 'i can speak {{ item }}'"
      loop:
        - Korean
        - English
      register: result 
    
    - name: Show result
      ansible.builtin.debug:
        msg: "Stdout: {{ item.stdout }}"
      loop: "{{ result.results }}"